package net.is_bg.ltf.db.common;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

class BindVariablePreparedStatementEx extends BindVariablePreparedStatement{
	String sql="";
	public BindVariablePreparedStatementEx(PreparedStatement pst, String sql) {
		super(pst);
		this.sql = sql;
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		boolean b =  super.execute(sql);
		return b;
	}
	
	@Override
	public ResultSet executeQuery() throws SQLException {
		ResultSet s =  super.executeQuery();
		return s;
	}
	
	
	@Override
	public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
		boolean b =  super.execute(sql, autoGeneratedKeys);
		return b;
	}
	
	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		boolean b = super.execute(sql, columnIndexes);
		return b;
	}
	
	@Override
	public boolean execute(String sql, String[] columnNames) throws SQLException {
		boolean b = super.execute(sql, columnNames);
		return b;
	}
	
	public String getSqlForLog(){
		String s =  getBindVarData().sqlForLog(sql);
		return s;
	}
	
	
}
