package net.is_bg.ltf.db.common;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;

public class BindVariablePreparedStatement implements PreparedStatement {
		
	private BindVariableData bindVarData = new BindVariableData();
	private PreparedStatement pst;
	
	public BindVariablePreparedStatement( PreparedStatement pst){
		this.pst = pst;
	}

	@Override
	public ResultSet executeQuery(String sql) throws SQLException {
		return pst.executeQuery(sql);
	}

	@Override
	public int executeUpdate(String sql) throws SQLException {
		return	pst.executeUpdate(sql);
	}

	@Override
	public void close() throws SQLException {
		pst.close();
	}

	@Override
	public int getMaxFieldSize() throws SQLException {
		return getMaxFieldSize();
	}

	@Override
	public void setMaxFieldSize(int max) throws SQLException {
		pst.setMaxFieldSize(max);
	}

	@Override
	public int getMaxRows() throws SQLException {
		return pst.getMaxRows();
	}

	@Override
	public void setMaxRows(int max) throws SQLException {
		pst.setMaxRows(max);
	}

	@Override
	public void setEscapeProcessing(boolean enable) throws SQLException {
		pst.setEscapeProcessing(enable);
	}

	@Override
	public int getQueryTimeout() throws SQLException {
		return pst.getQueryTimeout();
	}

	@Override
	public void setQueryTimeout(int seconds) throws SQLException {
		pst.setQueryTimeout(seconds);
	}

	@Override
	public void cancel() throws SQLException {
		pst.cancel();
	}

	@Override
	public SQLWarning getWarnings() throws SQLException {
		return pst.getWarnings();
	}

	@Override
	public void clearWarnings() throws SQLException {
		pst.clearWarnings();
	}

	@Override
	public void setCursorName(String name) throws SQLException {
		pst.setCursorName(name);
	}

	@Override
	public boolean execute(String sql) throws SQLException {
		return pst.execute(sql);
	}

	@Override
	public ResultSet getResultSet() throws SQLException {
		return	pst.getResultSet();
	}

	@Override
	public int getUpdateCount() throws SQLException {
		return pst.getUpdateCount();
	}

	@Override
	public boolean getMoreResults() throws SQLException {
		return pst.getMoreResults();
	}

	@Override
	public void setFetchDirection(int direction) throws SQLException {
		pst.setFetchDirection(direction);
	}

	@Override
	public int getFetchDirection() throws SQLException {
		return pst.getFetchDirection();
	}

	@Override
	public void setFetchSize(int rows) throws SQLException {
		pst.setFetchSize(rows);
	}

	@Override
	public int getFetchSize() throws SQLException {
		return pst.getFetchSize();
	}

	@Override
	public int getResultSetConcurrency() throws SQLException {
		return pst.getResultSetConcurrency();
	}

	@Override
	public int getResultSetType() throws SQLException {
		return pst.getResultSetType();
	}

	@Override
	public void addBatch(String sql) throws SQLException {
		pst.addBatch();
	}

	@Override
	public void clearBatch() throws SQLException {
		pst.clearBatch();
	}

	@Override
	public int[] executeBatch() throws SQLException {
		return pst.executeBatch();
	}

	@Override
	public Connection getConnection() throws SQLException {
		return pst.getConnection();
	}

	@Override
	public boolean getMoreResults(int current) throws SQLException {
		return pst.getMoreResults();
	}

	@Override
	public ResultSet getGeneratedKeys() throws SQLException {
		return pst.getGeneratedKeys();
	}

	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys)
			throws SQLException {
		return pst.executeUpdate(sql, autoGeneratedKeys);
	}

	@Override
	public int executeUpdate(String sql, int[] columnIndexes)
			throws SQLException {
		return pst.executeUpdate(sql, columnIndexes);
	}

	@Override
	public int executeUpdate(String sql, String[] columnNames)
			throws SQLException {
		return pst.executeUpdate(sql, columnNames);
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys)
			throws SQLException {
		return pst.execute(sql, autoGeneratedKeys);
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) throws SQLException {
		return pst.execute(sql, columnIndexes);
	}

	@Override
	public boolean execute(String sql, String[] columnNames)
			throws SQLException {
		return pst.execute(sql, columnNames);
	}

	@Override
	public int getResultSetHoldability() throws SQLException {
		return pst.getResultSetHoldability();
	}

	@Override
	public boolean isClosed() throws SQLException {
		return pst.isClosed();
	}

	@Override
	public void setPoolable(boolean poolable) throws SQLException {
		pst.setPoolable(poolable);
		
	}

	@Override
	public boolean isPoolable() throws SQLException {
		return pst.isPoolable();
	}

	@Override
	public void closeOnCompletion() throws SQLException {
		pst.closeOnCompletion();
	}

	@Override
	public boolean isCloseOnCompletion() throws SQLException {
		return pst.isCloseOnCompletion();
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		return pst.unwrap(iface);
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return pst.isWrapperFor(iface);
	}

	@Override
	public ResultSet executeQuery() throws SQLException {
		return pst.executeQuery();
	}

	@Override
	public int executeUpdate() throws SQLException {
		return pst.executeUpdate();
	}

	@Override
	public void setNull(int parameterIndex, int sqlType) throws SQLException {
		bindVarData.setNull(sqlType);
		pst.setNull(parameterIndex, sqlType);
	}

	@Override
	public void setBoolean(int parameterIndex, boolean x) throws SQLException {
		bindVarData.setBoolean(x, parameterIndex);
		pst.setBoolean(parameterIndex, x);
	}

	@Override
	public void setByte(int parameterIndex, byte x) throws SQLException {
		pst.setByte(parameterIndex, x);
	}

	@Override
	public void setShort(int parameterIndex, short x) throws SQLException {
		bindVarData.setShort( x, parameterIndex);
		pst.setShort(parameterIndex, x);
	}

	@Override
	public void setInt(int parameterIndex, int x) throws SQLException {
		bindVarData.setInt(x, parameterIndex);
		pst.setInt(parameterIndex, x);
	}

	@Override
	public void setLong(int parameterIndex, long x) throws SQLException {
		bindVarData.setLong(x, parameterIndex);
		pst.setLong(parameterIndex, x);
	}

	@Override
	public void setFloat(int parameterIndex, float x) throws SQLException {
		bindVarData.setFloat(x, parameterIndex);
		pst.setFloat(parameterIndex, x);
	}

	@Override
	public void setDouble(int parameterIndex, double x) throws SQLException {
		bindVarData.setDouble(x, parameterIndex);
		pst.setDouble(parameterIndex, x);
	}

	@Override
	public void setBigDecimal(int parameterIndex, BigDecimal x)
			throws SQLException {
		bindVarData.setBigDecimal(x, parameterIndex);
		pst.setBigDecimal(parameterIndex, x);
	}

	@Override
	public void setString(int parameterIndex, String x) throws SQLException {
		bindVarData.setString(x, parameterIndex);
		pst.setString(parameterIndex, x);
	}

	@Override
	public void setBytes(int parameterIndex, byte[] x) throws SQLException {
		pst.setBytes(parameterIndex, x);
	}

	@Override
	public void setDate(int parameterIndex, Date x) throws SQLException {
		bindVarData.setDate(x, parameterIndex);
		pst.setDate(parameterIndex, x);
	}

	@Override
	public void setTime(int parameterIndex, Time x) throws SQLException {
		bindVarData.setTime(x, parameterIndex);
		pst.setTime(parameterIndex, x);
	}

	@Override
	public void setTimestamp(int parameterIndex, Timestamp x)
			throws SQLException {
		bindVarData.setTimestamp(x, parameterIndex);
		pst.setTimestamp(parameterIndex, x);
	}

	@Override
	public void setAsciiStream(int parameterIndex, InputStream x, int length)
			throws SQLException {
		pst.setAsciiStream(parameterIndex, x, length);
	}

	@SuppressWarnings("deprecation")
	@Override
	public void setUnicodeStream(int parameterIndex, InputStream x, int length)
			throws SQLException {
		pst.setUnicodeStream(parameterIndex, x, length);
	}

	@Override
	public void setBinaryStream(int parameterIndex, InputStream x, int length)
			throws SQLException {
		pst.setBinaryStream(parameterIndex, x, length);
	}

	@Override
	public void clearParameters() throws SQLException {
		pst.clearParameters();
	}

	@Override
	public void setObject(int parameterIndex, Object x, int targetSqlType)
			throws SQLException {
		bindVarData.setObject(x, parameterIndex);
		pst.setObject(parameterIndex, x,  targetSqlType);
	}

	@Override
	public void setObject(int parameterIndex, Object x) throws SQLException {
		bindVarData.setObject(x, parameterIndex);
		pst.setObject(parameterIndex, x);
	}

	@Override
	public boolean execute() throws SQLException {
		return pst.execute();
	}

	@Override
	public void addBatch() throws SQLException {
		 pst.addBatch();
	}

	@Override
	public void setCharacterStream(int parameterIndex, Reader reader, int length)
			throws SQLException {
		pst.setCharacterStream(parameterIndex, reader, length);
	}

	@Override
	public void setRef(int parameterIndex, Ref x) throws SQLException {
		pst.setRef(parameterIndex, x);
	}

	@Override
	public void setBlob(int parameterIndex, Blob x) throws SQLException {
		pst.setBlob(parameterIndex, x);
	}

	@Override
	public void setClob(int parameterIndex, Clob x) throws SQLException {
		pst.setClob(parameterIndex, x);
	}

	@Override
	public void setArray(int parameterIndex, Array x) throws SQLException {
		pst.setArray(parameterIndex, x);
	}

	@Override
	public ResultSetMetaData getMetaData() throws SQLException {
		return pst.getMetaData();
	}

	@Override
	public void setDate(int parameterIndex, Date x, Calendar cal)
			throws SQLException {
		bindVarData.setDate(x, parameterIndex);
		pst.setDate(parameterIndex, x, cal);
	}

	@Override
	public void setTime(int parameterIndex, Time x, Calendar cal)
			throws SQLException {
		bindVarData.setTime(x, parameterIndex);
		pst.setTime(parameterIndex, x, cal);
	}

	@Override
	public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal)
			throws SQLException {
		bindVarData.setTimestamp(x, parameterIndex);
		pst.setTimestamp(parameterIndex, x, cal);
	}

	@Override
	public void setNull(int parameterIndex, int sqlType, String typeName)
			throws SQLException {
	    bindVarData.setNull(parameterIndex, sqlType);
		pst.setNull(parameterIndex, sqlType, typeName);
	}

	@Override
	public void setURL(int parameterIndex, URL x) throws SQLException {
		pst.setURL(parameterIndex, x);
	}

	@Override
	public ParameterMetaData getParameterMetaData() throws SQLException {
		return pst.getParameterMetaData();
	}

	@Override
	public void setRowId(int parameterIndex, RowId x) throws SQLException {
		pst.setRowId(parameterIndex, x);
	}

	@Override
	public void setNString(int parameterIndex, String value)
			throws SQLException {
		pst.setNString(parameterIndex, value);
	}

	@Override
	public void setNCharacterStream(int parameterIndex, Reader value,
			long length) throws SQLException {
		pst.setNCharacterStream(parameterIndex, value, length);
	}

	@Override
	public void setNClob(int parameterIndex, NClob value) throws SQLException {
		pst.setNClob(parameterIndex, value);
	}

	@Override
	public void setClob(int parameterIndex, Reader reader, long length)
			throws SQLException {
		pst.setClob(parameterIndex, reader, length);
	}

	@Override
	public void setBlob(int parameterIndex, InputStream inputStream, long length)
			throws SQLException {
		pst.setBlob(parameterIndex, inputStream, length);
	}

	@Override
	public void setNClob(int parameterIndex, Reader reader, long length)
			throws SQLException {
		pst.setNClob(parameterIndex, reader, length);
	}

	@Override
	public void setSQLXML(int parameterIndex, SQLXML xmlObject)
			throws SQLException {
		pst.setSQLXML(parameterIndex, xmlObject);
		
	}

	@Override
	public void setObject(int parameterIndex, Object x, int targetSqlType,
			int scaleOrLength) throws SQLException {
		bindVarData.setObject(x, parameterIndex);
		pst.setObject(parameterIndex, x, targetSqlType, scaleOrLength);
	}

	@Override
	public void setAsciiStream(int parameterIndex, InputStream x, long length)
			throws SQLException {
		pst.setAsciiStream(parameterIndex, x, length);
	}

	@Override
	public void setBinaryStream(int parameterIndex, InputStream x, long length)
			throws SQLException {
		pst.setBinaryStream(parameterIndex, x, length);
	}

	@Override
	public void setCharacterStream(int parameterIndex, Reader reader,
			long length) throws SQLException {
		pst.setCharacterStream(parameterIndex, reader, length);
	}

	@Override
	public void setAsciiStream(int parameterIndex, InputStream x)
			throws SQLException {
		pst.setAsciiStream(parameterIndex, x);
	}

	@Override
	public void setBinaryStream(int parameterIndex, InputStream x)
			throws SQLException {
		pst.setBinaryStream(parameterIndex, x);
	}

	@Override
	public void setCharacterStream(int parameterIndex, Reader reader)
			throws SQLException {
		pst.setCharacterStream(parameterIndex, reader);
	}

	@Override
	public void setNCharacterStream(int parameterIndex, Reader value)
			throws SQLException {
		pst.setNCharacterStream(parameterIndex, value);
	}

	@Override
	public void setClob(int parameterIndex, Reader reader) throws SQLException {
		pst.setClob(parameterIndex, reader);
	}

	@Override
	public void setBlob(int parameterIndex, InputStream inputStream)
			throws SQLException {
		pst.setBlob(parameterIndex, inputStream);
	}

	@Override
	public void setNClob(int parameterIndex, Reader reader) throws SQLException {
		pst.setNClob(parameterIndex, reader);
	}

	public BindVariableData getBindVarData() {
		return bindVarData;
	}
	
}
