package net.is_bg.ltf.db.common.client;

class PrepStatementAdditionalData implements IPrepStatementAdditionalData{
	String sql;
    int queryType = 1;     //1 select , 2 update, 3 stored proc, 4 batch
	int resultSetType;
	int resultSetConcurrency;
	int resultSetHoldability;
	int autoGeneratedKeys;
	int[] columnIndexes;
	String[] columnNames;
	
	@Override
	public String getSql() {
		return sql;
	}
	@Override
	public int getQueryType() {
		return queryType;
	}
	@Override
	public int getResultSetType() {
		return resultSetType;
	}
	@Override
	public int getResultSetConcurrency() {
		return resultSetConcurrency;
	}
	@Override
	public int getResultSetHoldability() {
		return resultSetHoldability;
	}
	@Override
	public int getAutoGeneratedKeys() {
		return autoGeneratedKeys;
	}
	@Override
	public int[] getColumnIndexes() {
		return columnIndexes;
	}
	@Override
	public String[] getColumnNames() {
		return columnNames;
	}
}
